markets:
  - currencies:
      primary: LEV
      secondary: ETH
    spread:
      type: fixed
      depth: 3
      quantity: 1
      step: 0.1
    trades:
      limit: 100
      timeout: 1000
    save_changes: true
gateways:
  Gatecoin:
    privateKey: missing
    publicKey: missing
    subscribeKey: sub-c-ee68e350-4ef7-11e6-bfbb-02ee2ddab7fe
    apiUrl: https://api.gatecoin.com
    timeout: 1000
