markets:
  - currencies:
      primary: LEV
      secondary: ETH
    spread:
      type: fixed
      depth: 5
      quantity: 10000
      step: 0.00001
    trades:
      limit: 100
      timeout: 1000
    save_changes: true
gateways:
  Gatecoin:
    privateKey: "must be provided via environment variable GATECOIN_PRIVATE_KEY"
    publicKey: missing
    subscribeKey: sub-c-ee68e350-4ef7-11e6-bfbb-02ee2ddab7fe
    apiUrl: https://api.gatecoin.com
    timeout: 1000
