markets:
  - currencies:
      primary: LEV
      secondary: ETH
    spread:
      type: fixed
      depth: 3
      quantity: 1
      step: 0.1
    trades:
      limit: 100
      timeout: 2000
    save_changes: false
gateways:
  Gatecoin: 
    publicKey: jUCWb9WNrNilduE4GKRB4NfIkcopMD5f
    apiUrl: https://api.gtcprojects.com
    timeout: 2000
    
  

